### ISSUE TITLE
xcodebuild args are not being passed to xcodebuild command

### ISSUE THREAD

**Issue by DamienBitrise** [bitrise-steplib/bitrise-step-xcode-test-without-building#4]
### Troubleshooting

- Which version of the step is effected? current
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Issue description

https://github.com/DamienBitrise/sample-swift-project-with-parallel-ui-test/blob/master/bitrise.yml#L67

Step does not add the additional xcodebuild args

Command output is:

`xcodebuild "test-without-building" "-xctestrun" "./test_bundle/BullsEye_FullTests_iphonesimulator15.5-arm64-x86_64.xctestrun" "-destination" "platform=iOS Simulator,name=iPhone 12 Pro Max" "-resultBundlePath" "/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/TestOutput3926229233/Test-BullsEye_FullTests_iphonesimulator15.5-arm64-x86_64.xcresult"`

### Bitrise info

- Build URL: https://app.bitrise.io/build/45932781-3b36-45db-950b-5a3e991649a3
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
+------------------------------------------------------------------------------+

| (0) xcode-test-without-building                                              |
+------------------------------------------------------------------------------+
| id: xcode-test-without-building                                              |
| version: 0.2.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2022-07-26T05:06:39Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[05:06:39]  * [OK] Step dependency (xcode) installed, available. 
Input:
- xctestrun: ./test_bundle/BullsEye_FullTests_iphonesimulator15.5-arm64-x86_64.xctestrun
- destination: platform=iOS Simulator,name=iPhone 12 Pro Max
- xcodebuild_options: -parallel-testing-enabled YES -maximum-parallel-testing-workers 3
- test_repetition_mode: none
- maximum_test_repetitions: 3
- relaunch_tests_for_each_repetition: false
- BITRISE_DEPLOY_DIR: /Users/vagrant/deploy
- BITRISE_TEST_RESULT_DIR: /var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/test_results1965003800/test_result2593922559
Running tests:
[05:06:40] xcodebuild "test-without-building" "-xctestrun" "./test_bundle/BullsEye_FullTests_iphonesimulator15.5-arm64-x86_64.xctestrun" "-destination" "platform=iOS Simulator,name=iPhone 12 Pro Max" "-resultBundlePath" "/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/TestOutput3926229233/Test-BullsEye_FullTests_iphonesimulator15.5-arm64-x86_64.xcresult"
  </pre>
</details>

### Steps to reproduce

1. Run the pipline
2. Parallel Simulators are not enabled

**Comment by hisaac** [comment]
We've just merged in a fix for this. I think we'll wait to do a proper release until @Bence1001 has time to write some unit tests, but pulling the Step using git will work until then.

**Comment by lpusok** [comment]
Fixed in https://github.com/bitrise-steplib/bitrise-step-xcode-test-without-building/releases/tag/0.2.1.
